apiVersion: apps/v1
kind: Deployment
metadata:
  name: neg-demo-app
  labels:
    app: neg-demo-app
spec:
  replicas: 3 # Đảm bảo tính khả dụng cao với nhiều bản sao
  selector:
    matchLabels:
      app: neg-demo-app
  template:
    metadata:
      labels:
        app: neg-demo-app
    spec:
      containers:
      - name: hostname
        image: registry.k8s.io/serve_hostname:v1.4
        ports:
        - containerPort: 9376
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /healthz
            port: 9376
          initialDelaySeconds: 3
          periodSeconds: 30
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: neg-demo-svc
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
  labels:
    app: neg-demo-app
spec:
  type: ClusterIP
  selector:
    app: neg-demo-app
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 9376
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: neg-demo-ing
spec:
  defaultBackend:
    service:
      name: neg-demo-svc
      port:
        number: 80
