apiVersion: v1
kind: Service
metadata:
  name: env-grouptest-ingress-service
  namespace: apigee
  annotations:
    cloud.google.com/app-protocols: '{"https":"HTTPS","http2":"HTTP"}'
    cloud.google.com/backend-config: '{"ports": {"443": "http-hc-config","80": "http-hc-config"}}'
    cloud.google.com/neg: '{"ingress": true}'
spec:
  ports:
  - name: status-port
    port: 15021
    protocol: TCP
    targetPort: 15021
  - name: http2
    port: 80
    protocol: TCP
    targetPort: 8080
  - name: https
    port: 443
    protocol: TCP
    targetPort: 8443
  selector:
    app: apigee-ingressgateway #required
    ingress_name: my-ingress-1
    org: prj-sa-team-apigee
  type: NodePort
---
apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: http-hc-config
  namespace: apigee
spec:
  healthCheck:
    checkIntervalSec: 15
    requestPath: /healthz/ingress
    port: 8443               # Sử dụng cổng 8443
    type: HTTPS              # Sử dụng HTTPS cho health check
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.global-static-ip-name: ip-elb-l7-apigee
    networking.gke.io/managed-certificates: "apigee-ssl-cert" # Chứng chỉ SSL do Google quản lý
  name: xlb-https-apigee-ingress
  namespace: apigee
spec:
  defaultBackend:
    service:
      name: env-grouptest-ingress-service
      port:
        number: 443 # Sử dụng cổng HTTPS
