# templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-app1-deployment
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: app1
  template:
    metadata:
      labels:
        app: app1
    spec:
      containers:
      - name: app1
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: {{ .Values.service.app1.targetPort }}
        livenessProbe:
          httpGet:
            path: /healthz
            port: {{ .Values.service.app1.targetPort }}
          initialDelaySeconds: 3
          periodSeconds: 30
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-app2-deployment
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: app2
  template:
    metadata:
      labels:
        app: app2
    spec:
      containers:
      - name: app2
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: {{ .Values.service.app2.targetPort }}
        livenessProbe:
          httpGet:
            path: /healthz
            port: {{ .Values.service.app2.targetPort }}
          initialDelaySeconds: 3
          periodSeconds: 30
