replicaCount: 3

image:
  repository: us-docker.pkg.dev/google-samples/containers/gke/hello-app
  tag: 1.0

service:
  app1:
    name: app1-service
    port: 80
    targetPort: 8080
  app2:
    name: app2-service
    port: 80
    targetPort: 8080

ingress:
  enabled: true
  staticIpName: "ip-ingress"
  managedCertificateName: "managed-cert-ingress"
  hosts:
    - host: app1.mrcloud.vn
      paths:
        - /
    - host: app2.mrcloud.vn
      paths:
        - /

frontendConfig:
  name: frontend-config
  redirectToHttps:
    enabled: true

backendConfig:
  app1:
    name: app1-backend-config
    healthCheck:
      checkIntervalSec: 30
      timeoutSec: 10
      healthyThreshold: 1
      unhealthyThreshold: 3
      type: HTTP
      requestPath: /healthz
      port: 8080
    timeoutSec: 30
    connectionDraining:
      drainingTimeoutSec: 60
  app2:
    name: app2-backend-config
    healthCheck:
      checkIntervalSec: 30
      timeoutSec: 10
      healthyThreshold: 1
      unhealthyThreshold: 3
      type: HTTP
      requestPath: /healthz
      port: 8080
    timeoutSec: 30
    connectionDraining:
      drainingTimeoutSec: 60
